### ISSUE TITLE
How long does it take to recon the 3D hair?

### ISSUE THREAD

**Issue by XinBlitz** [GAP-LAB-CUHK-SZ/HairStep#11]
Great work!

I'm curious about how long it takes to recon the 3D hair averagely.

Besides, when I try to run the recon3D, it would stuck in the trimesh.contains, is it normal to take a very long time for this?

**Comment by XinBlitz** [comment]
To be specific, it is line 83 in hair_util,py:

pts_in_out = mesh.contains(strands[i])

**Comment by PAULYZHENG** [comment]
About 1 minute per model. Remember to install the pyembree for accelerating the mesh.contain().

**Comment by XinBlitz** [comment]
Thanks for reply, and I've solved the problem

**Comment by Shan924** [comment]
> Thanks for reply, and I've solved the problem

Hello, I have also encountered the same problem as you. May I ask how you resolved it? I have installed pyebree but it still doesn't work.

**Comment by XinBlitz** [comment]
> > Thanks for reply, and I've solved the problem
> 
> Hello, I have also encountered the same problem as you. May I ask how you resolved it? I have installed pyebree but it still doesn't work.

I'm not realy know how to solve it for sure. In fact, my environment then is partly different from the given yaml file. So I create a new environment strictly  as same as the given environment, and this time the codes ran well.

**Comment by Shan924** [comment]
> > > Thanks for reply, and I've solved the problem
> > 
> > 
> > Hello, I have also encountered the same problem as you. May I ask how you resolved it? I have installed pyebree but it still doesn't work.
> 
> I'm not realy know how to solve it for sure. In fact, my environment then is partly different from the given yaml file. So I create a new environment strictly as same as the given environment, and this time the codes ran well.
Ok, many thanks for your help.

**Comment by Shan924** [comment]
> > > Thanks for reply, and I've solved the problem
> > 
> > 
> > Hello, I have also encountered the same problem as you. May I ask how you resolved it? I have installed pyebree but it still doesn't work.
> 
> I'm not realy know how to solve it for sure. In fact, my environment then is partly different from the given yaml file. So I create a new environment strictly as same as the given environment, and this time the codes ran well.

Ok, many thanks for your help!

**Comment by xqyd** [comment]
I was able to reproduce the authors statement: "About 1 minute per model. Remember to install the pyembree for accelerating the mesh.contain()." I cannot use the given yml since I was using Windows, here are my steps:

**conda create -n hairstep python=3.8
conda activate hairstep
pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
pip install -r requirements.txt**

remember to add **tqdm, rtree==1.0.0**, and **pyembree** into requirements.txt.

For building **3DDFA_V2**, you need to change **cpu_nms.pyx, line 25** to:
**cdef np.ndarray[np.int_t, ndim=1] order = scores.argsort()[::-1].astype('int32')**

otherwise you will run into the old error in Fast RCNN saying that <ValueError: Buffer dtype mismatch, expected 'int_t' but got 'long long’>

And you also need to **change np.bool to bool in sdf.py** since it was deprecated， otherwise the sdf won't work and you will get error of creating marching cube.

Hope these will help more people to check out this great work.

<img width="871" alt="image" src="https://github.com/GAP-LAB-CUHK-SZ/HairStep/assets/16912042/06b5b269-6a6b-4a1e-b009-c05387d58441">

**Comment by jayavanth** [comment]
@xqyd what did you use for the head model? Did you align the hair with the head manually?
